### ISSUE TITLE
Push version 1.1.0 to hex

### ISSUE THREAD

**Issue by dylanfareed** [BoweryFarming/peerage_ec2#13]
https://github.com/BoweryFarming/peerage_ec2/pull/12

**Comment by ksheurs** [comment]
Published! https://hex.pm/packages/peerage_ec2/1.1.0

I had to add `ex_doc` dep to publish, FYI. See 13a4e1e613cf30f694e2c99d52487d8258f3405f.

**Comment by dylanfareed** [comment]
Thanks @ksheurs!
