### ISSUE TITLE
Account for metadata API not always being available

### ISSUE THREAD

**Issue by ksheurs** [BoweryFarming/peerage_ec2#7]
Either a timeout issue or a timing issue (API not started yet).

**Comment by ksheurs** [comment]
I looked into how/when the metadata API would not be available. It's anytime the EC2 instance is not in the "ready" state. I think an instance normally coming online, the app booting, and then peerage polling is fine. I imagine the issue here if existing instances are bing cycled out during deploys or scaling. Will get a PR together to account for this!

**Comment by mrluc** [comment]
@ksheurs saw this announcement: https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-ecs-allows-containers-to-directly-access-environmental-metadata

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html

It's only good for self-knowledge, not knowledge of others (would only be helpful for templating node name etc) but they've probably implemented it in a way that means it's always available.

**Comment by ksheurs** [comment]
Interesting.. thanks @mrluc! I'm still unclear if Beanstalk+Docker runs on ECS under the hood (don't think it does), but I'll look more into this!

**Comment by mrluc** [comment]
It reads that way, though even if it is I don't know if the ECS underpinnings would be exposed in a meaningful way:

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_ecs.html#create_deploy_docker_ecs_resources
> When you create an environment using the multicontainer Docker platform, Elastic Beanstalk automatically creates and configures several Amazon EC2 Container Service resources while building the environment in order to create the necessary containers on each EC2 instance.

And http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_ecs.html#create_deploy_docker_ecs_role
> Elastic Beanstalk uses an Amazon ECS-optimized AMI with an Amazon ECS container agent that runs in a Docker container. The agent communicates with Amazon ECS to coordinate container deployments.
